version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem (e.g., "npm", "maven")
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Set the interval to "daily" or your preferred frequency
    labels:
      - "dependency-update" # Add a label to identify dependency update pull requests
    open-pull-requests-limit: 5 # Limit the number of open pull requests for dependency updates

graphs:
  - package-ecosystem: "" # Specify the package ecosystem for the dependency graph
    directory: "" # Location of package manifests
    output: "dependency-graph.png" # Output file for the dependency graph
    
