# To get started with Dependabot version updates, you'll need to specify which

      version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependency-graph" # Add a label to identify the dependency graph update
    open-pull-requests-limit: 5 # Limit the number of open pull requests for dependency updates

graphs:
  - package-ecosystem: "" # Specify the package ecosystem for the dependency graph
    directory: "/" # Location of package manifests
    output: "dependency-graph.png" # Output file for the dependency graph






