version: 2
updates:
  - package-ecosystem: "rubygems"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependency-update"
    open-pull-requests-limit: 5

graphs:
  - package-ecosystem: "rubygems"
    directory: "/"
    output: "dependency-graph.png"
